[project]
name = "codebase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nguyen Khac Giap", email = "nguyengiapnfif@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "discord-py>=2.7.1",
    "openai>=3.14.1",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
codebase = "codebase:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
